/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include "lcm/lcm_coretypes.h"

#ifndef __ckLcmType_DecisionDraw_t_hpp__
#define __ckLcmType_DecisionDraw_t_hpp__

#include <vector>

namespace ckLcmType
{

class DecisionDraw_t
{
    public:
        int32_t    num;

        std::vector< double > Path_x;

        std::vector< double > Path_y;

        int32_t    refnum;

        std::vector< double > Refer_x;

        std::vector< double > Refer_y;

        double     Tar_x;

        double     Tar_y;

        double     Cur_x;

        double     Cur_y;

        double     Cur_Angle;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "DecisionDraw_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int DecisionDraw_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DecisionDraw_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int DecisionDraw_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t DecisionDraw_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* DecisionDraw_t::getTypeName()
{
    return "DecisionDraw_t";
}

int DecisionDraw_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Path_x[0], this->num);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Path_y[0], this->num);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->refnum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->refnum > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Refer_x[0], this->refnum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->refnum > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Refer_y[0], this->refnum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Tar_x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Tar_y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Cur_x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Cur_y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Cur_Angle, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DecisionDraw_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->Path_x.resize(this->num);
    if(this->num) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Path_x[0], this->num);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->Path_y.resize(this->num);
    if(this->num) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Path_y[0], this->num);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->refnum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->Refer_x.resize(this->refnum);
    if(this->refnum) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Refer_x[0], this->refnum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->Refer_y.resize(this->refnum);
    if(this->refnum) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Refer_y[0], this->refnum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Tar_x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Tar_y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Cur_x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Cur_y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Cur_Angle, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DecisionDraw_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->num);
    enc_size += __double_encoded_array_size(NULL, this->num);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->refnum);
    enc_size += __double_encoded_array_size(NULL, this->refnum);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    return enc_size;
}

int64_t DecisionDraw_t::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0x2d19aab871494dbbLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
