#pragma once
#ifndef _PATH_PLANNING_LCM_SET_H
#define _PATH_PLANNING_LCM_SET_H


#define LCM_NET_LOCATION ""
#define LCM_CHANNEL_LOCATION "CKLOCATION"
#define LCM_NET_STATUS_BODY ""
#define LCM_CHANNEL_STATUS_BODY "CKSTATUS"
#define LCM_NET_VELO_GRID ""
#define LCM_CHANNEL_VELO_GRID "CKVELOGRID"
#define LCM_NET_CLOUD ""
#define LCM_CHANNEL_CLOUD "LASERCURB"
#define LCM_NET_CONTROL_COMMAND ""
#define LCM_CHANNEL_CONTROL_COMMAND "CKCONTROLCOMMAND"
#define LCM_NET_DECISION_DRAW ""
#define LCM_CHANNEL_DECISION_DRAW "CKDECISIONDRAW"

#endif // !_PATH_PLANNING_LCM_SET_H