/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include "lcm/lcm_coretypes.h"

#ifndef __ckLcmType_PlanOutput_hpp__
#define __ckLcmType_PlanOutput_hpp__

#include <vector>

namespace ckLcmType
{

class PlanOutput
{
    public:
        int32_t    tn;

        std::vector< double > TrajectoryX;

        std::vector< double > TrajectoryY;

        std::vector< double > TrajectoryAngle;

        std::vector< double > TrajectoryCost;

        std::vector< double > TrajectorySpeed;

        int8_t     status;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "PlanOutput"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int PlanOutput::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PlanOutput::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int PlanOutput::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t PlanOutput::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* PlanOutput::getTypeName()
{
    return "PlanOutput";
}

int PlanOutput::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->tn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->tn > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryX[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->tn > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryY[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->tn > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryAngle[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->tn > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryCost[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->tn > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->TrajectorySpeed[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->status, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PlanOutput::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->tn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->TrajectoryX.resize(this->tn);
    if(this->tn) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryX[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->TrajectoryY.resize(this->tn);
    if(this->tn) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryY[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->TrajectoryAngle.resize(this->tn);
    if(this->tn) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryAngle[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->TrajectoryCost.resize(this->tn);
    if(this->tn) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->TrajectoryCost[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->TrajectorySpeed.resize(this->tn);
    if(this->tn) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->TrajectorySpeed[0], this->tn);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->status, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PlanOutput::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->tn);
    enc_size += __double_encoded_array_size(NULL, this->tn);
    enc_size += __double_encoded_array_size(NULL, this->tn);
    enc_size += __double_encoded_array_size(NULL, this->tn);
    enc_size += __double_encoded_array_size(NULL, this->tn);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    return enc_size;
}

int64_t PlanOutput::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0x6ac40332b114a6e5LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
